### ISSUE TITLE
checkm data setRoot not working using singularity

### ISSUE THREAD

**Issue by alneberg** [nf-core/mag#13]
When running the pipeline with singularity i get this error when running the checkm process:

```
It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
You do not seem to have permission to edit the checkm config file
located at /opt/conda/envs/nf-core-mag-1.0.0/lib/python2.7/site-packages/checkm/DATA_CONFIG
Please try again with updated privileges. Error was:

[Errno 30] Read-only file system: '/opt/conda/envs/nf-core-mag-1.0.0/lib/python2.7/site-packages/checkm/DATA_CONFIG'
Sorry, CheckM cannot run without a valid data folder.

Unexpected error: <type 'exceptions.IOError'>
Traceback (most recent call last):
  File "/opt/conda/envs/nf-core-mag-1.0.0/bin/checkm", line 708, in <module>
    checkmParser.parseOptions(args)
  File "/opt/conda/envs/nf-core-mag-1.0.0/lib/python2.7/site-packages/checkm/main.py", line 1237, in parseOptions
    self.taxonSet(options)
  File "/opt/conda/envs/nf-core-mag-1.0.0/lib/python2.7/site-packages/checkm/main.py", line 262, in taxonSet
    bValidSet = taxonParser.markerSet(options.rank, options.taxon, options.marker_file)
  File "/opt/conda/envs/nf-core-mag-1.0.0/lib/python2.7/site-packages/checkm/taxonParser.py", line 82, in markerSet
    taxonMarkerSets = self.readMarkerSets()
  File "/opt/conda/envs/nf-core-mag-1.0.0/lib/python2.7/site-packages/checkm/taxonParser.py", line 40, in readMarkerSets
    for line in open(DefaultValues.TAXON_MARKER_SETS):
IOError: [Errno 2] No such file or directory: 'taxon_marker_sets.tsv'
```

For `checkm_download_db`, it doesn't crash (I get exitcode 0) but I still have the same issue when checking the log:
```
*******************************************************************************
 [CheckM - data] Check for database updates. [setRoot]
*******************************************************************************

Data location not changed
It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
You do not seem to have permission to edit the checkm config file
located at /opt/conda/envs/nf-core-mag-1.0.0/lib/python2.7/site-packages/checkm/DATA_CONFIG
Please try again with updated privileges. Error was:

[Errno 30] Read-only file system: '/opt/conda/envs/nf-core-mag-1.0.0/lib/python2.7/site-packages/checkm/DATA_CONFIG'
Sorry, CheckM cannot run without a valid data folder.
It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
You do not seem to have permission to edit the checkm config file
located at /opt/conda/envs/nf-core-mag-1.0.0/lib/python2.7/site-packages/checkm/DATA_CONFIG
Please try again with updated privileges. Error was:

[Errno 30] Read-only file system: '/opt/conda/envs/nf-core-mag-1.0.0/lib/python2.7/site-packages/checkm/DATA_CONFIG'
Sorry, CheckM cannot run without a valid data folder.
You do not seem to have permission to edit the checkm config file
located at /opt/conda/envs/nf-core-mag-1.0.0/lib/python2.7/site-packages/checkm/DATA_CONFIG
Please try again with updated privileges. Error was:

[Errno 30] Read-only file system: '/opt/conda/envs/nf-core-mag-1.0.0/lib/python2.7/site-packages/checkm/DATA_CONFIG'
```

Do you think this has to do something with user permission-differences between docker and singularity?

**Comment by alneberg** [comment]
For transparency, I used `--container 'hadrieng/mag:latest'` to run the pipeline.

**Comment by alneberg** [comment]
Closing due to the decision to ditch Checkm for Busco.
