### ISSUE TITLE
Self-test with Singularity - No such file: https://github.com/nf-core/test-datasets/raw/mag/test_data/minigut_cf.tar.gz

### ISSUE THREAD

**Issue by prehensilecode** [nf-core/mag#276]
## Check Documentation

I have checked the following places for your error:

- [✓] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [✓] [nf-core/mag pipeline documentation](https://nf-co.re/mag/usage)

## Description of the bug

Self-test with Singularity cannot find a test dataset.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: `nextflow run nf-core/mag -profile test,singularity &> OUTPUT.txt`
2. Error message: `No such file: https://raw.githubusercontent.com/nf-core/test-datasets/mag/test_data/minigut_cf.tar.gz`
3. HOWEVER, manual download (i.e. wget _url_) shows that file is there.

## Expected behaviour

Don't know: this was the self-test documented in `nf-core/mag/README.md`

## Log files

Have you provided the following extra information/files:

- [✓] The command used to run the pipeline
- [✓] The `.nextflow.log` file 

Abstract of `.nextflow.log`:
```
Feb-23 13:08:41.250 [main] DEBUG nextflow.cli.Launcher - $> nextflow run nf-core/mag -profile test,singularity
Feb-23 13:08:41.306 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 21.04.0
...
Feb-23 13:08:43.588 [main] DEBUG nextflow.cli.CmdRun -
  Version: 21.04.0 build 5552
  Created: 02-05-2021 16:22 UTC (12:22 EDT)
  System: Linux 4.18.0-147.el8.x86_64
  Runtime: Groovy 3.0.7 on OpenJDK 64-Bit Server VM 11.0.7+10-LTS
  Encoding: UTF-8 (UTF-8)
  Process: 80872@picotte001 [172.25.128.11]
  CPUs: 96 - Mem: 376.4 GB (12.8 GB) - Swap: 64 GB (61.7 GB)
...
------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/mag v2.1.1
------------------------------------------------------
Core Nextflow options
  revision                   : master
  runName                    : high_koch
  containerEngine            : singularity
  launchDir                  : /local/scratch/dwc62
  workDir                    : /local/scratch/dwc62/work
  projectDir                 : /home/dwc62/.nextflow/assets/nf-core/mag
  userName                   : dwc62
  profile                    : test,singularity
  configFiles                : /home/dwc62/.nextflow/assets/nf-core/mag/nextflow.config

Input/output options
  input                      : https://raw.githubusercontent.com/nf-core/test-datasets/mag/samplesheets/samplesheet.csv

Institutional config options
  config_profile_name        : Test profile
  config_profile_description : Minimal test dataset to check pipeline function

Max job request options
  max_cpus                   : 2
  max_memory                 : 6 GB
  max_time                   : 6h

Quality control for short reads options
  phix_reference             : /home/dwc62/.nextflow/assets/nf-core/mag/assets/data/GCA_002596845.1_ASM259684v1_genomic.fna.gz

Quality control for long reads options
  lambda_reference           : /home/dwc62/.nextflow/assets/nf-core/mag/assets/data/GCA_000840245.1_ViralProj14204_genomic.fna.gz

Taxonomic profiling options
  centrifuge_db              : https://raw.githubusercontent.com/nf-core/test-datasets/mag/test_data/minigut_cf.tar.gz
  kraken2_db                 : https://raw.githubusercontent.com/nf-core/test-datasets/mag/test_data/minigut_kraken.tgz
  skip_krona                 : true
  gtdb                       : false

Binning options
  min_length_unbinned_contigs: 1
  max_unbinned_contigs       : 2

Bin quality check options
  busco_reference            : https://busco-data.ezlab.org/v5/data/lineages/bacteria_odb10.2020-03-06.tar.gz
...
------------------------------------------------------
Feb-23 13:10:58.041 [main] DEBUG nextflow.Session - Session aborted -- Cause: https://raw.githubusercontent.com/nf-core/test-datasets/mag/test_data/minigut_cf.tar.gz
Feb-23 13:10:58.053 [main] DEBUG nextflow.Session - The following nodes are still active:
  [operator] splitCsv
  [operator] map

Feb-23 13:10:58.062 [main] ERROR nextflow.cli.Launcher - https://raw.githubusercontent.com/nf-core/test-datasets/mag/test_data/minigut_cf.tar.gz
java.nio.file.NoSuchFileException: https://raw.githubusercontent.com/nf-core/test-datasets/mag/test_data/minigut_cf.tar.gz
    at nextflow.file.FileHelper.checkIfExists(FileHelper.groovy:990)
    at nextflow.file.FileHelper$checkIfExists$1.call(Unknown Source)
    at nextflow.Nextflow.file(Nextflow.groovy:151)
    at nextflow.Nextflow$file$0.callStatic(Unknown Source)
    at Script_7dd4a75a.runScript(Script_7dd4a75a:31)
    at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:170)
    at nextflow.script.BaseScript.run(BaseScript.groovy:200)
    at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
    at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:207)
    at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:201)
    at nextflow.script.IncludeDef.memoizedMethodPriv$loadModule0PathMapSession(IncludeDef.groovy:142)
    at nextflow.script.IncludeDef.access$0(IncludeDef.groovy)
    at nextflow.script.IncludeDef$__clinit__closure1.doCall(IncludeDef.groovy)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
    at groovy.lang.Closure.call(Closure.java:412)
    at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
    at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
    at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
    at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
    at nextflow.script.IncludeDef.loadModule0(IncludeDef.groovy)
    at nextflow.script.IncludeDef.load0(IncludeDef.groovy:114)
    at nextflow.script.IncludeDef$load0$1.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
    at Script_d3fb58ae.runScript(Script_d3fb58ae:28)
    at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:170)
    at nextflow.script.BaseScript.run(BaseScript.groovy:200)
    at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:221)
    at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
    at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
    at nextflow.cli.CmdRun.run(CmdRun.groovy:302)
    at nextflow.cli.Launcher.run(Launcher.groovy:475)
    at nextflow.cli.Launcher.main(Launcher.groovy:657)
```

## System

- Hardware: Dell R640
- Executor: local
- OS: RHEL
- Version 8.1

## Nextflow Installation

- Version: 21.04.0

## Container engine

- Engine: Singularity
- version: 3.8.6

## Additional context

This was run on a server with connection to the internet, i.e. not an HPC cluster compute node.

**Comment by d4straub** [comment]
Hi there! 
Thanks for the report. I just tested `nextflow run nf-core/mag -r 2.1.1 -profile test,singularity` and it worked flawlessly. I assume there was a temporary issue with github/nextflow/internet connectivity. Nextflow is not 100% reliable with downloading data, usually its sufficient to try again.
Let me know if the pipeline works as expected at another time!

**Comment by prehensilecode** [comment]
Just re-ran it, and it completed fine. Thanks for checking!
