### ISSUE TITLE
yaml.scanner.ScannerError in "DUMPSOFTWAREVERSIONS" process

### ISSUE THREAD

**Issue by eray-sahin** [nf-core/mag#377]
### Description of the bug

Hello,

I am getting error during the process of "`NFCORE_MAG:MAG:CUSTOM_DUMPSOFTWAREVERSIONS", and the run is terminated with the error mesage below. As far as I understand, the problem might arise from the second colon in the version text of MetaBat2

"metabat2: MetaBAT: Metagenome Binning based on Abundance and Tetranucleotide frequency (version 2.12.1; Aug 31 2017 21:02:54)"

Can you please help me how to get rid of that problem or at least skip that process?

Thank you,

Best

### Command used and terminal output

```console
Traceback (most recent call last):
  File "/archive/eraysahin/nfcore/work/c1/67c516ef679977759a1d3998dc9ac1/.command.sh", line 54, in <module>
    versions_by_process = yaml.load(f, Loader=yaml.BaseLoader) | versions_this_module
  File "/home/eraysahin/anaconda3/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/eraysahin/anaconda3/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/eraysahin/anaconda3/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/eraysahin/anaconda3/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/eraysahin/anaconda3/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/eraysahin/anaconda3/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/eraysahin/anaconda3/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/eraysahin/anaconda3/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/eraysahin/anaconda3/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/eraysahin/anaconda3/lib/python3.8/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/eraysahin/anaconda3/lib/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/eraysahin/anaconda3/lib/python3.8/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/home/eraysahin/anaconda3/lib/python3.8/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "collated_versions.yml", line 102, column 22
```

### Relevant files

[collated_versions.yml.txt](https://github.com/nf-core/mag/files/10333869/collated_versions.yml.txt)

**Comment by d4straub** [comment]
Yes, that seems a problem with MetaBAT2 version parsing.
**In order to be able to fix that bug, could you please provide at least what package/container tool you used (conda/singularity/...) and what pipeline version?**

To ignore that error for now, append to the command to start the pipeline `-c ignore.config -resume` where `ignore.config` contains:
```
process {
    withName:CUSTOM_DUMPSOFTWAREVERSIONS {
      errorStrategy = 'ignore'
    }
}
```
that doesnt solve the problem itself but should let you finish the pipeline.

**Comment by eray-sahin** [comment]
Dear Dr. Straub, 

I did not use any profile, instead, used tools present in path of server, and the version of the pipeline is 2.2.1.

Best regards,

**Comment by jfy133** [comment]
Likely because you have installed an older version of metabat2:


```
NFCORE_MAG:MAG:BINNING:METABAT2_METABAT2":
    metabat2: MetaBAT: Metagenome Binning based on Abundance and Tetranucleotide frequency (version 2.12.1; Aug 31 2017 21:02:54)
```

But the pipeline uses 2.15. Likely the way that metabat2 reported the version changed, which is why it's failing to be 'cleaned up' by the pipeline.

This is one of the examples why nf-core strongly recommends using conda/singularity etc, because otherwise you can't guarantee reproducibility or execution (like this)
