### ISSUE TITLE
MAG_DEPTHS_PLOT issue

### ISSUE THREAD

**Issue by Vikash84** [nf-core/mag#383]
### Description of the bug

Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'NFCORE_MAG:MAG:BINNING:MAG_DEPTHS_PLOT (MEGAHIT-MetaBAT2-D22-41472-2_S6)'

Caused by:
  Process `NFCORE_MAG:MAG:BINNING:MAG_DEPTHS_PLOT (MEGAHIT-MetaBAT2-D22-41472-2_S6)` terminated with an error exit status (1)

Command executed:

  plot_mag_depths.py --bin_depths MEGAHIT-MetaBAT2-41472-2_S6-binDepths.tsv                     --groups sample_groups.tsv                     --out "MEGAHIT-MetaBAT2-41472-2_S6-binDepths.heatmap.png"
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MAG:MAG:BINNING:MAG_DEPTHS_PLOT":
      python: $(python --version 2>&1 | sed 's/Python //g')
      pandas: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('pandas').version)")
      seaborn: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('seaborn').version)")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/home/vsingh/.nextflow/assets/nf-core/mag/bin/plot_mag_depths.py", line 50, in 
      sys.exit(main())
    File "/home/vsingh/.nextflow/assets/nf-core/mag/bin/plot_mag_depths.py", line 45, in main
      sns.clustermap(df, row_cluster=True, yticklabels=bin_labels, cmap="vlag", center=0, col_colors=groups.group.map(color_map), figsize=(6,6))
    File "/usr/local/lib/python3.9/site-packages/seaborn/_decorators.py", line 46, in inner_f
      return f(**kwargs)
    File "/usr/local/lib/python3.9/site-packages/seaborn/matrix.py", line 1402, in clustermap
      return plotter.plot(metric=metric, method=method,
    File "/usr/local/lib/python3.9/site-packages/seaborn/matrix.py", line 1220, in plot
      self.plot_dendrograms(row_cluster, col_cluster, metric, method,
    File "/usr/local/lib/python3.9/site-packages/seaborn/matrix.py", line 1065, in plot_dendrograms
      self.dendrogram_row = dendrogram(
    File "/usr/local/lib/python3.9/site-packages/seaborn/_decorators.py", line 46, in inner_f
      return f(**kwargs)
    File "/usr/local/lib/python3.9/site-packages/seaborn/matrix.py", line 784, in dendrogram
      plotter = _DendrogramPlotter(data, linkage=linkage, axis=axis,
    File "/usr/local/lib/python3.9/site-packages/seaborn/matrix.py", line 594, in __init__
      self.linkage = self.calculated_linkage
    File "/usr/local/lib/python3.9/site-packages/seaborn/matrix.py", line 661, in calculated_linkage
      return self._calculate_linkage_scipy()
    File "/usr/local/lib/python3.9/site-packages/seaborn/matrix.py", line 629, in _calculate_linkage_scipy
      linkage = hierarchy.linkage(self.array, method=self.method,
    File "/usr/local/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 1068, in linkage
      n = int(distance.num_obs_y(y))
    File "/usr/local/lib/python3.9/site-packages/scipy/spatial/distance.py", line 2572, in num_obs_y
      raise ValueError("The number of observations cannot be determined on "
  ValueError: The number of observations cannot be determined on an empty distance matrix.

Work dir:
  /work/f3/7d3ba52b1375b555acf375a6671e9a

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by d4straub** [comment]
Hi there, looking at the error message, `ValueError: The number of observations cannot be determined on an empty distance matrix.` seems to be important. I assume there were no bins/mags identified? Could you check?

**Comment by Vikash84** [comment]
Hi Bins looks good

├── MetaBAT2
│   ├── bins
│   │   ├── MEGAHIT-MetaBAT2-D21-30002_S4.1.fa.gz
│   │   ├── MEGAHIT-MetaBAT2-D21-30002_S4.2.fa.gz
│   │   ├── MEGAHIT-MetaBAT2-D22-41472-2_S6.1.fa.gz
│   │   ├── MEGAHIT-MetaBAT2-D22-41745-4_S5.1.fa.gz
│   │   ├── SPAdes-MetaBAT2-D21-30002_S4.1.fa.gz
│   │   ├── SPAdes-MetaBAT2-D21-30002_S4.2.fa.gz
│   │   ├── SPAdes-MetaBAT2-D21-30002_S4.3.fa.gz
│   │   ├── SPAdes-MetaBAT2-D21-30002_S4.4.fa.gz
│   │   ├── SPAdes-MetaBAT2-D21-30002_S4.5.fa.gz
│   │   ├── SPAdes-MetaBAT2-D21-30002_S4.6.fa.gz
│   │   ├── SPAdes-MetaBAT2-D22-41472-2_S6.1.fa.gz
│   │   └── SPAdes-MetaBAT2-D22-41745-4_S5.1.fa.gz
│   ├── discarded
│   │   ├── MEGAHIT-MetaBAT2-D21-30002_S4.lowDepth.fa.gz
│   │   ├── MEGAHIT-MetaBAT2-D21-30002_S4.tooShort.fa.gz
│   │   ├── MEGAHIT-MetaBAT2-D22-41472-2_S6.lowDepth.fa.gz
│   │   ├── MEGAHIT-MetaBAT2-D22-41472-2_S6.tooShort.fa.gz
│   │   ├── MEGAHIT-MetaBAT2-D22-41745-4_S5.lowDepth.fa.gz
│   │   ├── MEGAHIT-MetaBAT2-D22-41745-4_S5.tooShort.fa.gz
│   │   ├── SPAdes-MetaBAT2-D21-30002_S4.lowDepth.fa.gz
│   │   ├── SPAdes-MetaBAT2-D21-30002_S4.tooShort.fa.gz
│   │   ├── SPAdes-MetaBAT2-D22-41472-2_S6.lowDepth.fa.gz
│   │   ├── SPAdes-MetaBAT2-D22-41472-2_S6.tooShort.fa.gz
│   │   ├── SPAdes-MetaBAT2-D22-41745-4_S5.lowDepth.fa.gz
│   │   └── SPAdes-MetaBAT2-D22-41745-4_S5.tooShort.fa.gz

**Comment by d4straub** [comment]
Indeed, there are bins! Could you check what `/work/f3/7d3ba52b1375b555acf375a6671e9a/MEGAHIT-MetaBAT2-41472-2_S6-binDepths.tsv` contains? Maybe there is an empty value, following `raise ValueError("The number of observations cannot be determined on "`?

**Comment by Vikash84** [comment]
/work/f3/7d3ba52b1375b555acf375a6671e9a/MEGAHIT-MetaBAT2-D22-41472-2_S6-binDepths.tsv

bin     D21-30002_S4    D22-41472-2_S6  D22-41745-4_S5
MEGAHIT-MetaBAT2-D22-41472-2_S6.1.fa    0.959122        186.333

**Comment by skrakau** [comment]
The script to generate the heat map showing the bin abundances across the samples expects at least two bins, and your file contains only one bin for this sample.

One can add a proper handling of such cases in the future, but is this something you expect, i.e. that it contains only one bin?

**Comment by alneberg** [comment]
Hello! I ran into the same issue as well. Thank you @skrakau  for the explanation, I think it make sense in my case as well. I was running a "test"-run with only a few samples to see that everything is set up properly on our cluster and then two of the samples resulted in only a single bin. These were 5 real samples, so I guess for someone with very few samples on a fairly complex community it could be a possible real scenario as well, not only a test-run.

**Comment by akaviaLab** [comment]
@jfy133 - currently closing this bug as a duplicate of #638, which was fixed in PR #639 on the workflow level.

**Comment by jfy133** [comment]
Thanks for the issue history 'archaeology' @akaviaLab , losing track of all the different issues itself 😅 🤦‍♂️
