### ISSUE TITLE
Issue with MAG_DEPTHS_PLOT

### ISSUE THREAD

**Issue by x-rv** [nf-core/mag#417]
I'm running mag in my institution's cluster and in the `MAG_DEPTHS_PLOT` step I run into the error `_tkinter.TclError: couldn't connect to display "localhost:11.0"`. 

For what I've read, I guess that's some issue related to X11. When I connect to the cluster via ssh I allow X11 since I have this written in my `.ssh/config`:
```
Host *
  ForwardAgent yes
  ForwardX11 yes
```

Do I need to start a X11 session before running the pipeline? But I can't since I'm not root of the cluster. What seems easiest for me is to skip this process in the pipeline, but I don't see any flag to do it and it's a required process for the pipeline to continue. Any ideas of what can I do or whether this skip flag could be added to the pipeline?

Here's the full error message:

```
Error executing process > 'NFCORE_MAG:MAG:BINNING:MAG_DEPTHS_PLOT (SPAdes-MaxBin2-test_minigut)'

Caused by:
  Process `NFCORE_MAG:MAG:BINNING:MAG_DEPTHS_PLOT (SPAdes-MaxBin2-test_minigut)` terminated with an error exit status (1)

Command executed:

  plot_mag_depths.py --bin_depths SPAdes-MaxBin2-test_minigut-binDepths.tsv                     --groups sample_groups.tsv                     
--out "SPAdes-MaxBin2-test_minigut-binDepths.heatmap.png"
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MAG:MAG:BINNING:MAG_DEPTHS_PLOT":
      python: $(python --version 2>&1 | sed 's/Python //g')
      pandas: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('pandas').version)")
      seaborn: $(python -c "import pkg_resources; print(pkg_resources.get_distribution('seaborn').version)")
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/home/xrey/.nextflow/assets/nf-core/mag/bin/plot_mag_depths.py", line 71, in <module>
      sys.exit(main())
    File "/home/xrey/.nextflow/assets/nf-core/mag/bin/plot_mag_depths.py", line 54, in main
      plt.figure()
    File "/home/xrey/miniconda3/envs/nf_mag/lib/python3.6/site-packages/matplotlib/pyplot.py", line 693, in figure
      **kwargs)
    File "/home/xrey/miniconda3/envs/nf_mag/lib/python3.6/site-packages/matplotlib/pyplot.py", line 315, in new_figure_manager
      return cls.new_figure_manager_given_figure(num, fig)
    File "/home/xrey/miniconda3/envs/nf_mag/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 885, in new_figure_manager_given_figure
      window = tk.Tk(className="matplotlib")
    File "/home/xrey/miniconda3/envs/nf_mag/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
      self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
  _tkinter.TclError: couldn't connect to display "localhost:11.0"

Work dir:
  /mnt/lustre/scratch/xrey/genomes/nextflow-mag/work/e7/09028286e27279854f9425097af44e

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

**Comment by d4straub** [comment]
Unfortunately I am not certain about the error itself, but it does sound like X11 forwarding to me as well. Maybe you can make sure that your pipeline and nextflow version are up to date and you are using one of the containerized solutions (I have no idea because you did not share the command line you used to start the pipeline).
I can however offer an immediate solution to ignore the failing of that steps. Append to your command `-resume -c ignore_depthplot.config` which contains:
```
process {
    withName: MAG_DEPTHS_PLOT {
        errorStrategy = 'ignore'
    }
}
```
that way you can at least get the remaining pipeline output. There is no command line flag to skip that step, as far as I am aware.

**Comment by x-rv** [comment]
> Unfortunately I am not certain about the error itself, but it does sound like X11 forwarding to me as well. Maybe you can make sure that your pipeline and nextflow version are up to date and you are using one of the containerized solutions (I have no idea because you did not share the command line you used to start the pipeline). I can however offer an immediate solution to ignore the failing of that steps. Append to your command with that you start the pipeline `-resume -c ignore_depthplot.config` where the config contains:
> 
> ```
> process {
>     withName: MAG_DEPTHS_PLOT {
>         errorStrategy = 'ignore'
>     }
> }
> ```
> 
> that way you can at least get the remaining pipeline output. There is no command line flag to skip that step, as far as I am aware.

Thank you! I will try this command. 

It's true that I forgot to report the initial command, I didn't consider it necessary, but it's `nextflow run nf-core/mag -profile test,slurm`. I can't use containers in the cluster I'm working with, so I install every requirement previously in a conda environment. I might have to install X11 or something there (?). I know it's not the optimal way of running it, but here I don't have a choice.

**Comment by d4straub** [comment]
> I can't use containers in the cluster I'm working with, so I install every requirement previously in a conda environment. I might have to install X11 or something there (?). I know it's not the optimal way of running it, but here I don't have a choice.

I see. For me, one of the biggest advantages of nf-core pipelines are the simplicity of software requirements when using container software. E.g. running a nf-core pipeline on the cluster that I have never used before is as trivial as writing the command line to start it because nextflow & singularity are taking care of all other software. I absolutely recommend you to contact you sysadmin and request singularity on your cluster.
If its just a matter of having no internet connection, have a look at https://nf-co.re/usage/offline.

> It's true that I forgot to report the initial command, I didn't consider it necessary, but it's nextflow run nf-core/mag -profile test,slurm. 

I recommend using `-r <version>` so you control the pipeline version explicitly. Also the nextflow version can matter, because older versions or "edge" versions can cause trouble.

**Comment by dialvarezs** [comment]
I'm going to close this, since  we removed MAG_DEPTH_PLOTS in #1018
