### ISSUE TITLE
How to run in an offline environment?

### ISSUE THREAD

**Issue by IvanWoo22** [nf-core/mag#482]
### Description of the bug

When I run `mag` on the `LSF` platform that is not connected to the public network, an error is always reported during the `Nextflow` initialization phase: `ERROR o.p.update.DefaultUpdateRepository - raw.githubusercontent.com`, but this problem does not occur when running other (such as `rnaseq`) . Is this a `mag` setting problem? So how do I run it in a non-network environment?

### Command used and terminal output

```console
nextflow run mag/workflow --input mag_samplesheet.csv --outdir mag_output -profile singularity -resume --max_cpus 24 --kraken2_db kraken2.tgz
```

### Relevant files

Jul-28 10:44:13.056 [main] DEBUG nextflow.cli.Launcher - $> nextflow run mag/workflow --input mag_samplesheet.csv --outdir mag_output -profile singularity -resume --max_cpus 24 --kraken2_db kraken2.tgz
Jul-28 10:44:13.203 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.04.1
Jul-28 10:44:13.239 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/share/home/wangq/.nextflow/plugins; core-plugins: nf-amazon@1.16.2,nf-azure@1.0.1,nf-codecommit@0.1.4,nf-console@1.0.5,nf-ga4gh@1.0.5,nf-google@1.7.3,nf-tower@1.5.12,nf-wave@0.8.2
Jul-28 10:44:13.272 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jul-28 10:44:13.273 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jul-28 10:44:13.276 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Jul-28 10:44:13.288 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jul-28 10:44:16.003 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /share/home/wangq/wyf/mag/mag/workflow/nextflow.config
Jul-28 10:44:16.004 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /share/home/wangq/wyf/mag/mag/workflow/nextflow.config
Jul-28 10:44:16.032 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity`
Jul-28 10:44:19.447 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [cfc_dev, ifb_core, denbi_qbic, alice, mjolnir_globe, uppmax, test_binning_entry, incliva, uge, rosalind_uge, test_nothing, lugh, unibe_ibu, vai, czbiohub_aws, jax, ccga_med, scw, tigem, tubingen_apg, google, ipop_up, googlels, eddie, medair, test_host_rm, biowulf, apptainer, bi, bigpurple, sbc_sharc, adcra, cedars, vsc_kul_uhasselt, pawsey_nimbus, ucl_myriad, utd_ganymede, charliecloud, icr_davros, test_ancient_dna, ceres, munin, arm, rosalind, test_binrefinement, hasta, cfc, uzh, test_hybrid_host_rm, test_busco_auto, ebi_codon_slurm, ebc, ku_sund_dangpu, ccga_dx, test_hybrid, crick, marvin, biohpc_gen, shifter, mana, mamba, wehi, awsbatch, imperial, maestro, genotoul, test_no_clipping, abims, janelia, nu_genomics, googlebatch, oist, sahmri, mpcdf, leicester, vsc_ugent, sage, cambridge, podman, ebi_codon, cheaha, xanadu, test, computerome, seg_globe, sanger, dkfz, pasteur, test_full, azurebatch, hki, test_adapterremoval, crukmi, docker, engaging, gis, hypatia, psmn, eva, fgcz, conda, crg, singularity, uw_hyak_pedslabs, prince, utd_sysbio, debug, genouest, cbe, test_bbnorm, phoenix, gitpod, seawulf, fub_curta, uct_hpc, aws_tower, binac]
Jul-28 10:44:19.456 [main] WARN  nextflow.config.ConfigBuilder - It appears you have never run this project before -- Option `-resume` is ignored
Jul-28 10:44:19.554 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declararion
Jul-28 10:44:19.585 [main] INFO  nextflow.cli.CmdRun - Launching `mag/workflow/main.nf` [focused_wilson] DSL2 - revision: 41a9c631f4
Jul-28 10:44:19.586 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins declared=[nf-validation]
Jul-28 10:44:19.586 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jul-28 10:44:19.586 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[nf-validation]
Jul-28 10:44:19.586 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-validation version: latest
Jul-28 10:44:20.071 [main] ERROR o.p.update.DefaultUpdateRepository - raw.githubusercontent.com
java.net.UnknownHostException: raw.githubusercontent.com
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at org.pf4j.update.DefaultUpdateRepository.initPlugins(DefaultUpdateRepository.java:96)
	at org.pf4j.update.DefaultUpdateRepository.getPlugins(DefaultUpdateRepository.java:80)
	at org.pf4j.update.UpdateManager.getPluginsMap(UpdateManager.java:149)
	at org.pf4j.update.UpdateManager.getLastPluginRelease(UpdateManager.java:392)
	at nextflow.plugin.PluginUpdater.load0(PluginUpdater.groovy:320)
	at nextflow.plugin.PluginUpdater.installPlugin(PluginUpdater.groovy:197)
	at nextflow.plugin.PluginUpdater.prepareAndStart(PluginUpdater.groovy:144)
	at nextflow.plugin.PluginsFacade.start(PluginsFacade.groovy:328)
	at nextflow.plugin.PluginsFacade.start(PluginsFacade.groovy:333)
	at nextflow.plugin.PluginsFacade.load(PluginsFacade.groovy:232)
	at nextflow.plugin.Plugins.load(Plugins.groovy:56)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:331)
	at nextflow.cli.Launcher.run(Launcher.groovy:494)
	at nextflow.cli.Launcher.main(Launcher.groovy:653)
Jul-28 10:44:20.083 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.IllegalStateException: Cannot find latest version of nf-validation plugin
	at nextflow.plugin.PluginUpdater.load0(PluginUpdater.groovy:322)
	at nextflow.plugin.PluginUpdater.installPlugin(PluginUpdater.groovy:197)
	at nextflow.plugin.PluginUpdater.prepareAndStart(PluginUpdater.groovy:144)
	at nextflow.plugin.PluginsFacade.start(PluginsFacade.groovy:328)
	at nextflow.plugin.PluginsFacade.start(PluginsFacade.groovy:333)
	at nextflow.plugin.PluginsFacade.load(PluginsFacade.groovy:232)
	at nextflow.plugin.Plugins.load(Plugins.groovy:56)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:331)
	at nextflow.cli.Launcher.run(Launcher.groovy:494)
	at nextflow.cli.Launcher.main(Launcher.groovy:653)

### System information

HPC

**Comment by prototaxites** [comment]
There's some documentation on the nf-core website about running pipelines offline: https://nf-co.re/docs/usage/offline

Give those a shot and let us know if you're still having issues!

**Comment by jfy133** [comment]
@IvanWoo22 does the same happen if you run with `-r dev` ?
