### ISSUE TITLE
SPAdes errors with >1000GB RAM

### ISSUE THREAD

**Issue by d4straub** [nf-core/mag#61]
SPAdes expects for '--memory' an int() with GB, but nextflow changes >1000GB to 1.TB and therefore '--memory' receives an int() or non-int with TB and this leads to a failure.

```
Error message:
Caused by:
  Process `spades (QMFCE004AVQMFCE027A1QMFCE028A9)` terminated with an error exit status (1)

Command executed:

  metaspades.py         --threads "64"         --memory "1.5T"         --pe1-1 QMFCE004AVQMFCE027A1QMFCE028A9_unmapped_1.fastq.gz         --pe1-2 QMFCE004AVQMFCE027A1QMFCE028A9_unmapped_2.fastq.gz         -o spades
  mv spades/assembly_graph_with_scaffolds.gfa QMFCE004AVQMFCE027A1QMFCE028A9_graph.gfa
  mv spades/scaffolds.fasta QMFCE004AVQMFCE027A1QMFCE028A9_scaffolds.fasta
  mv spades/contigs.fasta QMFCE004AVQMFCE027A1QMFCE028A9_contigs.fasta
  mv spades/spades.log QMFCE004AVQMFCE027A1QMFCE028A9_log.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-mag-1.0.0/bin/metaspades.py", line 1102, in <module>
      main(sys.argv)
    File "/opt/conda/envs/nf-core-mag-1.0.0/bin/metaspades.py", line 651, in main
      cfg, dataset_data = fill_cfg(options, log)
    File "/opt/conda/envs/nf-core-mag-1.0.0/bin/metaspades.py", line 297, in fill_cfg
      options_storage.memory = int(arg)
  ValueError: invalid literal for int() with base 10: '1.5T'
```

Untested possible solution:
Instead of
`def maxmem = "${task.memory.toString().replaceAll(/[\sGB]/,'')}"`
use
`def maxmem = "${task.memory.toGiga().toString().replaceAll(/[\sGB]/,'')}"`

**Comment by maxibor** [comment]
`.toGiga()` should be enough, no ?

```groovy
groovy> mem = new MemoryUnit('1.5 T') 
groovy> print(mem.toGiga()) 
1536
```

See also: https://github.com/nextflow-io/nextflow/blob/master/modules/nf-commons/src/test/nextflow/util/MemoryUnitTest.groovy#L115-L118

So 
```groovy
maxmem = task.memory.toGiga()
```

**Comment by skrakau** [comment]
Thanks @maxibor !
