### ISSUE TITLE
`--megahit_options` doesnt work as intended

### ISSUE THREAD

**Issue by d4straub** [nf-core/mag#709]
### Description of the bug

With version 3.2.0 and the introduction of the MEGAHIT nf-core module, setting `--megahit_options` make the pipeline fail, as below.
The issue seems to be a missing white space in https://github.com/nf-core/mag/blob/74b5c92b9226d3ae19c20ed9f1d107e9273c0d00/conf/modules.config#L260, it should be instead `{ params.megahit_options ? params.megahit_options + " -m ${task.memory.toBytes()}" : "-m ${task.memory.toBytes()}" }`.

### Command used and terminal output

```
ERROR ~ Error executing process > 'NFCORE_MAG:MAG:MEGAHIT (group-all)'

Caused by:
  Process `NFCORE_MAG:MAG:MEGAHIT (group-all)` terminated with an error exit status (1)


Command executed:

  megahit \
      -1 QUNGA248A3_run0_phix_removed.unmapped_1.fastq.gz,QUNGA246AL_run0_phix_removed.unmapped_1.fastq.gz,QUNGA255AK_run0_phix_removed.unmapped_1.fastq.gz,QUNGA241AF_run0_phix_removed.unmapped_1.fastq.g
z,QUNGA254AC_run0_phix_removed.unmapped_1.fastq.gz,QUNGA252AU_run0_phix_removed.unmapped_1.fastq.gz,QUNGA242AN_run0_phix_removed.unmapped_1.fastq.gz,QUNGA243AV_run0_phix_removed.unmapped_1.fastq.gz,QUNGA
253A4_run0_phix_removed.unmapped_1.fastq.gz,QUNGA249AB_run0_phix_removed.unmapped_1.fastq.gz,QUNGA256AS_run0_phix_removed.unmapped_1.fastq.gz,QUNGA251AM_run0_phix_removed.unmapped_1.fastq.gz,QUNGA244A5_r
un0_phix_removed.unmapped_1.fastq.gz,QUNGA247AT_run0_phix_removed.unmapped_1.fastq.gz,QUNGA261AT_run0_phix_removed.unmapped_1.fastq.gz,QUNGA250AE_run0_phix_removed.unmapped_1.fastq.gz,QUNGA245AD_run0_phi
x_removed.unmapped_1.fastq.gz,QUNGA260AL_run0_phix_removed.unmapped_1.fastq.gz,QUNGA264AJ_run0_phix_removed.unmapped_1.fastq.gz,QUNGA257A2_run0_phix_removed.unmapped_1.fastq.gz,QUNGA259AI_run0_phix_remov
ed.unmapped_1.fastq.gz,QUNGA262A3_run0_phix_removed.unmapped_1.fastq.gz,QUNGA263AB_run0_phix_removed.unmapped_1.fastq.gz,QUNGA258AA_run0_phix_removed.unmapped_1.fastq.gz -2 QUNGA248A3_run0_phix_removed.u
nmapped_2.fastq.gz,QUNGA246AL_run0_phix_removed.unmapped_2.fastq.gz,QUNGA255AK_run0_phix_removed.unmapped_2.fastq.gz,QUNGA241AF_run0_phix_removed.unmapped_2.fastq.gz,QUNGA254AC_run0_phix_removed.unmapped
_2.fastq.gz,QUNGA252AU_run0_phix_removed.unmapped_2.fastq.gz,QUNGA242AN_run0_phix_removed.unmapped_2.fastq.gz,QUNGA243AV_run0_phix_removed.unmapped_2.fastq.gz,QUNGA253A4_run0_phix_removed.unmapped_2.fast
q.gz,QUNGA249AB_run0_phix_removed.unmapped_2.fastq.gz,QUNGA256AS_run0_phix_removed.unmapped_2.fastq.gz,QUNGA251AM_run0_phix_removed.unmapped_2.fastq.gz,QUNGA244A5_run0_phix_removed.unmapped_2.fastq.gz,QU
NGA247AT_run0_phix_removed.unmapped_2.fastq.gz,QUNGA261AT_run0_phix_removed.unmapped_2.fastq.gz,QUNGA250AE_run0_phix_removed.unmapped_2.fastq.gz,QUNGA245AD_run0_phix_removed.unmapped_2.fastq.gz,QUNGA260A
L_run0_phix_removed.unmapped_2.fastq.gz,QUNGA264AJ_run0_phix_removed.unmapped_2.fastq.gz,QUNGA257A2_run0_phix_removed.unmapped_2.fastq.gz,QUNGA259AI_run0_phix_removed.unmapped_2.fastq.gz,QUNGA262A3_run0_
phix_removed.unmapped_2.fastq.gz,QUNGA263AB_run0_phix_removed.unmapped_2.fastq.gz,QUNGA258AA_run0_phix_removed.unmapped_2.fastq.gz \
      --min-contig-len 500 --k-list 29,37,47,57,67,77,87,97,107,117-m 2040109465600 \
      -t 128 \
      --out-prefix MEGAHIT-group-all
  
  pigz \
      --no-name \
      -p 128 \
       \
      megahit_out/*.fa \
      megahit_out/intermediate_contigs/*.fa
  
  mv megahit_out/* .
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MAG:MAG:MEGAHIT":
      megahit: $(echo $(megahit -v 2>&1) | sed 's/MEGAHIT v//')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  Traceback (most recent call last):
    File "/opt/conda/bin/megahit", line 1038, in <module>
      main()
    File "/opt/conda/bin/megahit", line 977, in main
      parse_option(argv[1:])
    File "/opt/conda/bin/megahit", line 369, in parse_option
      opt.k_list = list(map(int, value.split(',')))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ValueError: invalid literal for int() with base 10: '117-m'

```

**Comment by jfy133** [comment]
Done in https://github.com/nf-core/mag/pull/710/
